// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNYf5TLhPUwhvC46e2VH68_nR8h4_aP7E',
    appId: '1:837352973262:web:792f64908e3761fe31419f',
    messagingSenderId: '837352973262',
    projectId: 'ecom-c08b0',
    authDomain: 'ecom-c08b0.firebaseapp.com',
    storageBucket: 'ecom-c08b0.appspot.com',
    measurementId: 'G-XX382FBL6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYDo4KyFGoSbkKdxMai6_s8gKTRJGQpVo',
    appId: '1:837352973262:android:815d978d6718da5b31419f',
    messagingSenderId: '837352973262',
    projectId: 'ecom-c08b0',
    storageBucket: 'ecom-c08b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgqAitSh_fm3fqAtgHtD0tTJS3k1B5yWE',
    appId: '1:837352973262:ios:0b949338ac95557331419f',
    messagingSenderId: '837352973262',
    projectId: 'ecom-c08b0',
    storageBucket: 'ecom-c08b0.appspot.com',
    iosBundleId: 'com.example.ecom',
  );
}
